apiVersion: apps/v1
kind: Deployment
metadata:
  name: smaksdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smt-aks-app
  template:
    metadata:
      labels:
        app: smt-aks-app
    spec:
      containers:
        - name: smt-aks-demo
          image: acr4javacontappdana.azurecr.io/sangmins:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: smt-aks-app
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
  selector:
    app: smt-aks-app
  type: LoadBalancer
